const KEY="biupiu-rnd-os-v1";let db=JSON.parse(localStorage.getItem(KEY)||'{"research":[],"experiments":[],"assets":[],"audit":[]}');const $=id=>document.getElementById(id);
function save(){localStorage.setItem(KEY,JSON.stringify(db));render()}
function id(p){return p+"-"+crypto.randomUUID().slice(0,8).toUpperCase()}
function audit(action,ref){db.audit.push({id:id("AUD"),action,ref,at:new Date().toISOString()})}
function esc(s){return String(s||"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
function render(){ $("researchCount").textContent=db.research.length;$("experimentCount").textContent=db.experiments.length;$("assetCount").textContent=db.assets.length;$("auditCount").textContent=db.audit.length;
$("researchList").innerHTML=db.research.map(x=>'<div class="item"><b>'+esc(x.title)+'</b><div class="meta">'+x.id+' · '+x.class+' · '+x.at+'</div><p>'+esc(x.notes)+'</p></div>').join("")||"<p>No research objects yet.</p>";
$("experimentList").innerHTML=db.experiments.map(x=>'<div class="item"><b>'+esc(x.title)+'</b><div class="meta">'+x.id+' · '+x.at+'</div><p><b>Hypothesis:</b> '+esc(x.hypothesis)+'</p><p>'+esc(x.protocol)+'</p></div>').join("")||"<p>No experiments yet.</p>";
$("assetList").innerHTML=db.assets.map(x=>'<div class="item"><b>'+esc(x.name)+'</b><div class="meta">'+x.id+' · '+x.assetClass+' · '+x.status+'</div><p>Research: '+esc(x.researchId||"—")+' · Algorithm: '+esc(x.algorithm||"—")+'</p><button onclick="downloadAsset(\\''+x.id+'\\')">Export mint payload</button><pre>'+esc(JSON.stringify(x.payload,null,2))+'</pre></div>').join("")||"<p>No digital assets yet.</p>"}
$("tabs").onclick=e=>{if(!e.target.dataset.tab)return;document.querySelectorAll(".panel").forEach(x=>x.classList.remove("active"));$(e.target.dataset.tab).classList.add("active")}
$("researchForm").onsubmit=e=>{e.preventDefault();const x={id:id("RES"),title:$("rTitle").value,class:$("rClass").value,notes:$("rNotes").value,at:new Date().toISOString()};db.research.push(x);audit("CREATE_RESEARCH",x.id);e.target.reset();save()}
$("experimentForm").onsubmit=e=>{e.preventDefault();const x={id:id("EXP"),title:$("eTitle").value,hypothesis:$("eHypothesis").value,protocol:$("eProtocol").value,at:new Date().toISOString(),status:"LOGGED"};db.experiments.push(x);audit("CREATE_EXPERIMENT",x.id);e.target.reset();save()}
$("assetForm").onsubmit=async e=>{e.preventDefault();const x={id:id("AST"),name:$("aName").value,researchId:$("aResearch").value,algorithm:$("aAlgorithm").value,assetClass:$("aClass").value,licence:$("aLicence").value,status:"READY_FOR_REVIEW",at:new Date().toISOString()};const canonical={asset_id:x.id,name:x.name,research_id:x.researchId||null,algorithm:x.algorithm||null,class:x.assetClass,licence:x.licence,created_at:x.at,gate:x.status};x.payload={...canonical,sha256:await digest(JSON.stringify(canonical))};db.assets.push(x);audit("CREATE_ASSET_MINT_PAYLOAD",x.id);e.target.reset();save()}
async function digest(s){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function downloadAsset(assetId){const x=db.assets.find(a=>a.id===assetId);const blob=new Blob([JSON.stringify(x.payload,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=assetId+"-mint-payload.json";a.click();URL.revokeObjectURL(a.href);audit("EXPORT_MINT_PAYLOAD",assetId);save()}
$("exportBtn").onclick=()=>{const blob=new Blob([JSON.stringify(db,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="biupiu-rnd-os-workspace.json";a.click();URL.revokeObjectURL(a.href)}
$("resetBtn").onclick=()=>{if(confirm("Reset local workspace? This cannot be undone.")){localStorage.removeItem(KEY);location.reload()}}
if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");render();