"""PROP-17 evidence-aware state engine.

Data-governance layer: simulations/plans cannot silently become validated claims.
No physical measurements are generated by this module.
"""
from dataclasses import dataclass
from typing import Optional, Dict, Any


VALID_STATES = ("planned", "measured", "bench_tested", "validated", "certified")


@dataclass
class Observation:
    test_id: str
    metric: str
    planned: Optional[float] = None
    measured: Optional[float] = None
    uncertainty: Optional[float] = None
    status: str = "planned"


def compare(obs: Observation) -> Dict[str, Any]:
    if obs.measured is None:
        return {"test_id": obs.test_id, "metric": obs.metric,
                "status": "NO_MEASURED_DATA", "delta": None}
    delta = None if obs.planned is None else obs.measured - obs.planned
    return {"test_id": obs.test_id, "metric": obs.metric,
            "status": "MEASURED_PENDING_REVIEW", "delta": delta,
            "uncertainty": obs.uncertainty}


def state_transition(current: str, evidence_complete: bool,
                     review_passed: bool) -> str:
    if current not in VALID_STATES:
        raise ValueError(f"unknown state: {current}")
    if current in ("validated", "certified"):
        return current
    if evidence_complete and review_passed:
        return "validated"
    if evidence_complete:
        return "bench_tested"
    return current


def anomaly(obs: Observation, tolerance: float = 0.10) -> Dict[str, Any]:
    if obs.measured is None or obs.planned is None:
        return {"test_id": obs.test_id, "metric": obs.metric,
                "flag": "INSUFFICIENT_DATA"}
    if obs.planned == 0:
        return {"test_id": obs.test_id, "metric": obs.metric,
                "flag": "REVIEW_REQUIRED" if obs.measured != 0 else "WITHIN_SCREENING_TOLERANCE"}
    relative = abs(obs.measured - obs.planned) / abs(obs.planned)
    return {"test_id": obs.test_id, "metric": obs.metric,
            "flag": "REVIEW_REQUIRED" if relative > tolerance else "WITHIN_SCREENING_TOLERANCE",
            "relative_deviation": relative}


def validate_record(record: Dict[str, Any]) -> Dict[str, Any]:
    required = ("test_id", "module", "application", "validation_status")
    missing = [k for k in required if k not in record]
    status = record.get("validation_status")
    errors = []
    if missing:
        errors.extend(f"MISSING:{k}" for k in missing)
    if status not in VALID_STATES:
        errors.append("INVALID_VALIDATION_STATUS")
    # A record cannot claim validation without explicit measured evidence and review.
    if status in ("validated", "certified"):
        if record.get("measured_evidence_complete") is not True:
            errors.append("VALIDATED_REQUIRES_MEASURED_EVIDENCE")
        if record.get("review_passed") is not True:
            errors.append("VALIDATED_REQUIRES_REVIEW")
    return {"valid": not errors, "errors": errors}
