"""AI-53 canonical Biupiu gate-state machine.

Single source of truth for legal state transitions. Fail-closed.
"""
from __future__ import annotations

STATES=("DISCOVERED","ASSIGNED","EXECUTING","CHALLENGED","VALIDATED",
        "REGRESSION_PASS","PROMOTION_READY","PROMOTED",
        "PENDING_RUNTIME","REMEDIATION_REQUIRED","BLOCKED_UNTRUSTED_EVIDENCE",
        "BLOCKED_CONTROL_CONTRACT")

TRANSITIONS={
 "DISCOVERED":{"ASSIGNED","BLOCKED_CONTROL_CONTRACT"},
 "ASSIGNED":{"EXECUTING","BLOCKED_CONTROL_CONTRACT"},
 "EXECUTING":{"CHALLENGED","PENDING_RUNTIME","REMEDIATION_REQUIRED"},
 "CHALLENGED":{"VALIDATED","REMEDIATION_REQUIRED"},
 "VALIDATED":{"REGRESSION_PASS","REMEDIATION_REQUIRED"},
 "REGRESSION_PASS":{"PROMOTION_READY","REMEDIATION_REQUIRED"},
 "PROMOTION_READY":{"PROMOTED","REMEDIATION_REQUIRED"},
 "PROMOTED":set(),
 "PENDING_RUNTIME":{"EXECUTING","REMEDIATION_REQUIRED"},
 "REMEDIATION_REQUIRED":{"EXECUTING","BLOCKED_CONTROL_CONTRACT"},
 "BLOCKED_UNTRUSTED_EVIDENCE":{"EXECUTING","REMEDIATION_REQUIRED"},
 "BLOCKED_CONTROL_CONTRACT":{"ASSIGNED","EXECUTING"}
}

def allowed(current,nxt):
    return nxt in TRANSITIONS.get(current,set())

def validate_path(path):
    return len(path)>=1 and all(a in STATES and b in STATES and allowed(a,b)
                                 for a,b in zip(path,path[1:]))
