name: Biupiu R&D OS API CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'software/rnd-os-api/**'
      - '.github/workflows/rnd-os-api-ci.yml'
  pull_request:
    paths:
      - 'software/rnd-os-api/**'
      - '.github/workflows/rnd-os-api-ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: software/rnd-os-api/server
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm test
